name: Go test

on:
  pull_request:
    branches: ["main"]

jobs:
  golang-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: "false"

      - name: Test
        run: make test
